---

nginx:
    image: {{ docker_user }}/nginx:dev
    ports:
        - "80:80"
        - "443:443"

reg:
    image: {{ docker_user }}/core:dev
    ports:
        - "5000:5000"
    environment:
# error handling is currently broken in gunicorn + flask + flask_restufl
# see https://github.com/flask-restful/flask-restful/issues/542 and https://github.com/flask-restful/flask-restful/pull/544
#        server: gunicorn
        api: reg
    volumes:
        - ./abaco.conf:/etc/abaco.conf
        - /home/apim/logs/reg.log:/var/log/abaco.log

mes:
    image: {{ docker_user }}/core:dev
    ports:
        - "5001:5000"
    environment:
#        server: gunicorn
        api: mes
    volumes:
        - ./abaco.conf:/etc/abaco.conf
        - /home/apim/logs/mes.log:/var/log/abaco.log

agavemes:
    image: {{ docker_user }}/core:dev
    ports:
        - "5002:5000"
    environment:
        server: dev
        api: agavemes
    volumes:
        - ./abaco.conf:/etc/abaco.conf
        - /home/apim/logs/agavemes.log:/var/log/abaco.log

admin:
    image: {{ docker_user }}/core:dev
    ports:
        - "5003:5000"
    environment:
#        server: gunicorn
        api: admin
    volumes:
        - ./abaco.conf:/etc/abaco.conf
        - /home/apim/logs/admin.log:/var/log/abaco.log

