---

nginx:
    image: {{ docker_user }}/nginx:{{ abaco_tag }}
    ports:
        - "80:80"
        - "443:443"

reg:
    image: {{ docker_user }}/core:{{ abaco_tag }}
    ports:
        - "5000:5000"
    environment:
# error handling is currently broken in gunicorn + flask + flask_restufl
# see https://github.com/flask-restful/flask-restful/issues/542 and https://github.com/flask-restful/flask-restful/pull/544
#        server: gunicorn
        server: {{ web_server_type }}
        api: reg
        mongo_password:
        redis_password:
    volumes:
        - ./abaco.conf:/etc/service.conf
        - /home/apim/logs/reg.log:/var/log/service.log

mes:
    image: {{ docker_user }}/core:{{ abaco_tag }}
    ports:
        - "5001:5000"
    environment:
#        server: gunicorn
        server: {{ web_server_type }}
        api: mes
        mongo_password:
        redis_password:
    volumes:
        - ./abaco.conf:/etc/service.conf
        - /home/apim/logs/mes.log:/var/log/service.log

agavemes:
    image: {{ docker_user }}/core:{{ abaco_tag }}
    ports:
        - "5002:5000"
    environment:
        server: {{ web_server_type }}
        api: agavemes
        mongo_password:
        redis_password:
    volumes:
        - ./abaco.conf:/etc/service.conf
        - /home/apim/logs/agavemes.log:/var/log/service.log

admin:
    image: {{ docker_user }}/core:{{ abaco_tag }}
    ports:
        - "5003:5000"
    environment:
#        server: gunicorn
        server: {{ web_server_type }}
        api: admin
        mongo_password:
        redis_password:
    volumes:
        - ./abaco.conf:/etc/service.conf
        - /home/apim/logs/admin.log:/var/log/service.log

